# Generated by Django 3.2.2 on 2021-10-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
