# Generated by Django 3.2.2 on 2021-10-29 03:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_socialpost_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('tipe', models.CharField(choices=[('TITULO', 'TITULO'), ('SUBTITULO', 'SUBTITULO'), ('PARRAFO', 'PARRAFO'), ('IMAGEN', 'IMAGEN'), ('CODIGO', 'CODIGO')], default='TITULO', max_length=15)),
                ('create_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to=social.models.user_directory_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialpost')),
            ],
        ),
    ]
