# Generated by Django 3.2.2 on 2021-10-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_bodypost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodypost',
            old_name='tipe',
            new_name='type',
        ),
    ]
