# Generated by Django 3.2.2 on 2021-10-29 03:45

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_tipe_bodypost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=social.models.user_directory_path),
        ),
    ]
