# Generated by Django 3.2.2 on 2021-10-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_bodypost_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
