# Generated by Django 3.2.2 on 2021-10-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_bodypost_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodypost',
            old_name='img',
            new_name='imagen',
        ),
    ]
