# Generated by Django 3.2.2 on 2021-10-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_rename_img_bodypost_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='body',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='image',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='label',
            field=models.CharField(choices=[('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('FLEX', 'FLEX'), ('EXCEL', 'EXCEL'), ('SISTEMA OPERATIVO', 'SISTEMA OPERATIVO'), ('MATEMATICAS', 'MATEMATICAS'), ('PROBLEMAS RESUELTOS', 'PROBLEMAS RESUELTOS'), ('LOGICA', 'LOGICA'), ('C++', 'C++'), ('VIDEOJUEGOS', 'VIDEOJUEGOS'), ('LIBRERIA', 'LIBRERIA')], default='PYTHON', max_length=60),
        ),
    ]
