# Generated by Django 3.2.2 on 2021-10-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20211029_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='label',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='label',
            field=models.ManyToManyField(to='social.Tags'),
        ),
    ]
