# Generated by Django 3.2.2 on 2021-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20211029_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAF', 'DRAF')], default='DRAF', max_length=15),
        ),
    ]
