# Generated by Django 3.2.2 on 2021-11-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_socialpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('DRAF', 'DRAF'), ('PENDING', 'PENDING')], default='DRAF', max_length=15),
        ),
    ]
