# Generated by Django 3.2.2 on 2021-11-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_savepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavePost',
        ),
    ]
